export const BASE_ELEMENT_PRICE: number = 10000;
export const BASE_ELEMENTS_PRICES: Record<string, number> = {
    AqLM9JqF5wv5DZynY8CducahkB7JWPxWpDL29TPRwmNV: BASE_ELEMENT_PRICE, // Air
    DyYYN86vMZy6E8MVYEcrRTHwMJk5z66iDTPhHBYAafc2: BASE_ELEMENT_PRICE, // Earth
    H1PLKchzLBgMNMnHLV15NScrMoXJXkgbCog2WnLxzjHn: BASE_ELEMENT_PRICE, // Fire
    Bw4iN1gCvzmdiY9WfuEG1QJaxheTXif2fxuqQ5KQR2zT: BASE_ELEMENT_PRICE, // Water
};
